#!/bin/bash
set -e

echo "👉 Running ToFu pre-commit checks..."

# Check formatting
tofu fmt -check -recursive
if [ $? -ne 0 ]; then
  echo "❌ ToFu files not formatted. Run 'tofu fmt -recursive'."
  exit 1
fi

# Validate configs
tofu validate
if [ $? -ne 0 ]; then
  echo "❌ Tofu validation failed."
  exit 1
fi

echo "✅ Pre-commit checks passed."
